### ISSUE TITLE
error when trying to install via composer

### ISSUE THREAD

**Issue by VickG** [gmo/salesforce-rest-api#3]
[master_swebupujze]:public_html$ composer config repositories.salesforce-rest-api vcs https://github.com/gmo/salesforce-rest-api
[master_swebupujze]:public_html$ composer require "gmo/salesforce-rest-api:^1.0"./composer.json has been updated                                   
Loading composer repositories with package information
Updating dependencies (including require-dev)                      
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for psr/log (locked at 1.1.0) -> satisfiable by psr/log[1.1.0].
    - gmo/salesforce-rest-api v1.0.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.0.1 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.0.2 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.1.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.1.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.0.2 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.0.1 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - gmo/salesforce-rest-api v1.0.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Conclusion: don't install psr/log 1.0.0
    - Installation request for gmo/salesforce-rest-api ^1.0 -> satisfiable by gmo/salesforce-rest-api[v1.0.0, v1.0.1, v1.0.2, v1.1.0].
Installation failed, reverting ./composer.json to its original content.

**Comment by mikegillis677** [comment]
Okay, I made an update to the composer.json to not be so restrictive.  Try now.

**Comment by VickG** [comment]
@mikegillis677 getting same error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/event-dispatcher (locked at v4.2.4) -> satisfiable by symfony/event-dispatcher[v4.2.4].
    - gmo/salesforce-rest-api v1.0.0 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.0.1 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.0.2 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.1.0 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.1.1 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.1.0 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.0.2 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.0.1 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api v1.0.0 requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - gmo/salesforce-rest-api 1.x-dev requires guzzle/guzzle 3.9.2 -> satisfiable by guzzle/guzzle[v3.9.2].
    - Conclusion: don't install guzzle/guzzle v3.9.2
    - Installation request for gmo/salesforce-rest-api ^1.0 -> satisfiable by gmo/salesforce-rest-api[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.1.1, 1.x-dev].


Installation failed, reverting ./composer.json to its original content.

**Comment by mikegillis677** [comment]
It looks like this new issue is that your composer.json prevents you from using an older version of guzzle.  This package is being maintained to provide a programmable interface to Salesforce for systems that are restricted to older versions of guzzle for whatever reason.  There are other Salesforce API SDKs that might meet your needs better.

**Comment by VickG** [comment]
@mikegillis677 ok got it, I tried about 3-4 packages, so far none of them has worked.
